---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
  - name: remove apache lib mod php
    apt:
      name: libapache2-mod-php
      state: absent
